luku1 = int(input("1 numero: "))
luku2 = int(input("2 numero: "))
luku3 = int(input("3 numero: "))

print("summa:")
print(luku1 + luku2 + luku3)
print("tulo:")
print(luku1 * luku2 * luku3)
print("keskiarvo:")
print((luku1 + luku2 + luku3) / 3)
